import { contextBridge, ipcRenderer, webUtils } from 'electron';

contextBridge.exposeInMainWorld('vaultApi', {
  getAppVersion: () => ipcRenderer.invoke('app:getVersion'),
  getLicenseStatus: () => ipcRenderer.invoke('license:status'),
  activateLicense: (key: string) => ipcRenderer.invoke('license:activate', key),
  getLogs: () => ipcRenderer.invoke('app:getLogs'),
  openLogs: () => ipcRenderer.invoke('app:openLogs'),
  openVaultDataFolder: () => ipcRenderer.invoke('app:openVaultDataFolder'),
  openExternal: (url: string) => ipcRenderer.invoke('app:openExternal', url),
  getDashboardSummary: () => ipcRenderer.invoke('dashboard:summary'),
  getPathForFile: (file: File) => webUtils.getPathForFile(file),
  listItems: (args?: { search?: string; tag?: string; type?: string; collectionId?: string; mediaOnly?: boolean; imageOnly?: boolean; videoOnly?: boolean; audioOnly?: boolean; documentOnly?: boolean; favoriteOnly?: boolean; limit?: number; offset?: number; sort?: string }) => ipcRenderer.invoke('items:list', args),
  getItem: (id: string) => ipcRenderer.invoke('items:get', id),
  listTags: () => ipcRenderer.invoke('tags:list'),
  createTag: (name: string) => ipcRenderer.invoke('tags:create', name),
  renameTag: (oldName: string, newName: string) => ipcRenderer.invoke('tags:rename', { oldName, newName }),
  deleteTag: (name: string) => ipcRenderer.invoke('tags:delete', name),
  listCollections: () => ipcRenderer.invoke('collections:list'),
  createCollection: (args: string | { name: string; mode?: string; parentId?: string }) => ipcRenderer.invoke('collections:create', args),
  setCollectionParent: (args: { id: string; parentId: string }) => ipcRenderer.invoke('collections:setParent', args),
  deleteCollection: (id: string) => ipcRenderer.invoke('collections:delete', id),
  listRelationships: (itemId: string) => ipcRenderer.invoke('relationships:list', itemId),
  listAllRelationships: () => ipcRenderer.invoke('relationships:listAll'),
  listMemories: () => ipcRenderer.invoke('memories:list'),
  getMemory: (id: string) => ipcRenderer.invoke('memories:get', id),
  listMemorySuggestions: () => ipcRenderer.invoke('memories:suggestions'),
  createMemory: (args: { title: string; description?: string; theme?: string; itemIds?: string[] }) => ipcRenderer.invoke('memories:create', args),
  deleteMemory: (id: string) => ipcRenderer.invoke('memories:delete', id),
  updateMemory: (args: { id: string; title?: string; description?: string; theme?: string; coverItemId?: string }) => ipcRenderer.invoke('memories:update', args),
  updateMemoryPlayerPosition: (args: { id: string; x: number; y: number }) => ipcRenderer.invoke('memories:updatePlayerPosition', args),
  addItemToMemory: (args: { memoryId: string; itemId: string }) => ipcRenderer.invoke('memories:addItem', args),
  removeItemFromMemory: (args: { memoryId: string; itemId: string }) => ipcRenderer.invoke('memories:removeItem', args),
  updateMemoryLayout: (args: { memoryId: string; items: { itemId: string; x: number; y: number; width?: number; height?: number }[] }) => ipcRenderer.invoke('memories:updateLayout', args),
  addMemoryDecoration: (args: { memoryId: string; kind: string; label?: string; color?: string }) => ipcRenderer.invoke('memories:addDecoration', args),
  updateMemoryDecoration: (args: { memoryId: string; id: string; x?: number; y?: number; width?: number; height?: number; rotation?: number; label?: string; color?: string }) => ipcRenderer.invoke('memories:updateDecoration', args),
  removeMemoryDecoration: (args: { memoryId: string; id: string }) => ipcRenderer.invoke('memories:removeDecoration', args),
  listLocations: () => ipcRenderer.invoke('locations:list'),
  getMapTileBaseUrl: () => ipcRenderer.invoke('locations:getMapTileBaseUrl'),
  downloadMapTiles: (tiles: { z: number; x: number; y: number }[]) => ipcRenderer.invoke('locations:downloadMapTiles', tiles),
  addRelationship: (args: { itemId: string; relatedItemId: string; note?: string }) => ipcRenderer.invoke('relationships:add', args),
  removeRelationship: (args: { itemId: string; relatedItemId: string }) => ipcRenderer.invoke('relationships:remove', args),
  createNote: (args: { title: string; body?: string; tags?: string[] | string; collectionIds?: string[] }) => ipcRenderer.invoke('items:createNote', args),
  updateItem: (args: { id: string; title?: string; body?: string; tags?: string[] | string; favorite?: boolean; private?: boolean; imageRotation?: number; createdAt?: string; collectionIds?: string[] }) => ipcRenderer.invoke('items:update', args),
  deleteItem: (id: string) => ipcRenderer.invoke('items:delete', id),
  deleteItems: (ids: string[]) => ipcRenderer.invoke('items:deleteMany', ids),
  addTagsToItems: (ids: string[], tags: string[]) => ipcRenderer.invoke('items:addTags', ids, tags),
  removeTagsFromItems: (ids: string[], tags: string[]) => ipcRenderer.invoke('items:removeTags', ids, tags),
  addCollectionToItems: (ids: string[], collectionId: string) => ipcRenderer.invoke('items:addCollection', ids, collectionId),
  previewImport: (files: { sourcePath: string; relativePath?: string }[]) => ipcRenderer.invoke('items:previewImport', files),
  importGooglePhotosTakeout: () => ipcRenderer.invoke('items:importGooglePhotosTakeout'),
  importNotionExport: (args?: { sourceType?: 'zip' | 'folder' }) => ipcRenderer.invoke('items:importNotionExport', args),
  repairGooglePhotosMetadata: () => ipcRenderer.invoke('items:repairGooglePhotosMetadata'),
  onGooglePhotosImportProgress: (callback: (progress: { phase: string; current: number; total: number; fileName?: string; imported?: number; matchedMetadata?: number; skipped?: number }) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, progress: { phase: string; current: number; total: number; fileName?: string; imported?: number; matchedMetadata?: number; skipped?: number }) => callback(progress);
    ipcRenderer.on('googlePhotosImport:progress', listener);
    return () => ipcRenderer.removeListener('googlePhotosImport:progress', listener);
  },
  onBackupImportProgress: (callback: (progress: { phase: string; current: number; total: number; fileName?: string; imported?: number }) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, progress: { phase: string; current: number; total: number; fileName?: string; imported?: number }) => callback(progress);
    ipcRenderer.on('backupImport:progress', listener);
    return () => ipcRenderer.removeListener('backupImport:progress', listener);
  },
  uploadFile: (args: { sourcePath: string; title?: string; body?: string; tags?: string[] | string; collectionIds?: string[] }) => ipcRenderer.invoke('items:uploadFile', args),
  getMediaUrl: (id: string) => ipcRenderer.invoke('items:getMediaUrl', id),
  openFile: (id: string) => ipcRenderer.invoke('items:openFile', id),
  reindexFiles: () => ipcRenderer.invoke('items:reindexFiles'),
  exportBackup: () => ipcRenderer.invoke('backup:export'),
  openBackupFolder: () => ipcRenderer.invoke('backup:openFolder'),
  getBackupSettings: () => ipcRenderer.invoke('backup:getSettings'),
  chooseBackupFolder: () => ipcRenderer.invoke('backup:chooseFolder'),
  setBackupFrequency: (frequency: string) => ipcRenderer.invoke('backup:setFrequency', frequency),
  setBackupRetentionCount: (count: number) => ipcRenderer.invoke('backup:setRetentionCount', count),
  setBackupEncryption: (args: { enabled: boolean; password?: string }) => ipcRenderer.invoke('backup:setEncryption', args),
  setImportTagSuggestions: (allowNewTags: boolean) => ipcRenderer.invoke('settings:setImportTagSuggestions', allowNewTags),
  importBackup: (args?: { password?: string }) => ipcRenderer.invoke('backup:import', args),
  listWatchedFolders: () => ipcRenderer.invoke('watched:list'),
  addWatchedFolder: () => ipcRenderer.invoke('watched:addFolder'),
  removeWatchedFolder: (id: string) => ipcRenderer.invoke('watched:removeFolder', id),
  scanWatchedFolders: (args?: { markSeen?: boolean; folderId?: string }) => ipcRenderer.invoke('watched:scan', args),
  markWatchedFilesSeen: (files: { sourcePath: string; watchedFolderId?: string; watchedFolderPath?: string }[]) => ipcRenderer.invoke('watched:markSeen', files),
  markWatchedScanHandled: (args?: { folderId?: string }) => ipcRenderer.invoke('watched:markScanHandled', args),
  checkForUpdates: () => ipcRenderer.invoke('updates:check')
});
